imports:
  - {resource: phpcsfixer.rules.yml }

parameters:
  process_timeout: 3600
  ascii:
    failed: ~
    succeeded: ~

  # PHP Code Sniffer parameters.
  tasks.phpcs.ignore_patterns:
    - vendor/
    - node_modules/
    - tests/fixtures/
  tasks.phpcs.triggered_by:
    - inc
    - install
    - module
    - php
    - profile
    - theme
  tasks.phpcs.whitelist_patterns: []
  tasks.phpcs.standard: ./vendor/drupal/coder/coder_sniffer/Drupal
  tasks.phpcs.warning_severity: ~

  # PHP CS Fixer parameters
  tasks.phpcsfixer2.config: ./vendor/drupol/drupal-conventions/config/drupal8/php_cs_fixer.config.php
  tasks.phpcsfixer2.rules: %phpcsfixer.rules%


  # Tasks.
  tasks:
    # PHP Code Sniffer.
    phpcs:
      standard: '%tasks.phpcs.standard%'
      ignore_patterns: '%tasks.phpcs.ignore_patterns%'
      triggered_by: '%tasks.phpcs.triggered_by%'
      whitelist_patterns: '%tasks.phpcs.whitelist_patterns%'
      warning_severity: '%tasks.phpcs.warning_severity%'
      metadata:
        priority: 300

    # PHP CS Fixer
    phpcsfixer2:
      config: '%tasks.phpcsfixer2.config%'
      rules: '%tasks.phpcsfixer2.rules%'
      config_contains_finder: true
      verbose: true
      allow_risky: true
      using_cache: false

    yamllint:
      whitelist_patterns: []
      ignore_patterns: []
      object_support: true
      exception_on_invalid_type: true
      parse_constant: true
      parse_custom_tags: true

    jsonlint:
      ignore_patterns: []
      detect_key_conflicts: true
